### PR TITLE
docs(examples): consistency Improvement of 3 Nodes Example

### PR DESCRIPTION
**Pull request by dora-gt**
Previous discussions are found here: #208

### CODE REVIEW

**Comment by dora-gt** [comment]
Close and reopen #208

**Comment by dora-gt** [comment]
I'll check why the tests fail.

**Comment by dora-gt** [comment]
Fixed some settlement engine tests because we changed the meaning of `settlement_threshold`. I tried not to change the whole structure, just adjusting the values.

**Comment by dora-gt** [comment]
Could you take a glance at the tests? @emschwartz or @gakonst

**Comment by emschwartz** [comment]
Looks good to me

**Pull request merged**
